import { useEffect, useState } from 'react';
type Status = {oura:{configured:boolean;connected:boolean;lastSync:string|null;scopes:string[]};apple:{connected:boolean;lastSync:string|null;expires:number|null}};
async function request(path:string,method='GET') {
  const response=await fetch('/api/wearables'+path,{method,headers:{'X-PulseSense-Request':'1'}});
  const body=await response.json();if(!response.ok)throw new Error(body.error||'Wearable request failed.');return body;
}
export default function Wearables({onImported}:{onImported:()=>Promise<void>}){
 const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[pair,setPair]=useState<{code:string;expires:number}|null>(null);
 async function refresh(){setStatus(await request(''));}
 useEffect(()=>{void refresh().catch(e=>setError(e.message));const p=new URLSearchParams(location.search);if(p.get('wearable')==='oura'){setMessage(p.get('result')==='connected'?'Oura connected. Choose Sync last 7 days to import readings.':'Oura connection was cancelled.');history.replaceState(null,'',location.pathname);}},[]);
 async function act(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const synced=(value:string|null)=>value?'Last synced '+new Date(value).toLocaleString():'No readings synced yet';
 return <><header className="page-heading"><div><div className="eyebrow">READINGS FROM YOUR DEVICES</div><h1>Wearables</h1><p>Connect your ring or import Apple Watch readings through Apple Health.</p></div><button className="secondary" disabled={busy} onClick={()=>void act(async()=>{await refresh();await onImported();})}>Refresh status</button></header>
 {error&&<div className="error" role="alert">{error}</div>}{message&&<div className="notice" role="status">{message}</div>}
 {!status?<p>Loading connections…</p>:<div className="two-column">
 <section className="panel"><span className="large-symbol">◯</span><h2>Oura Ring</h2><p>Import heart rate samples, sleep HRV and respiratory averages, and nightly oxygen averages when available.</p><div className="notice">{status.oura.connected?'Connected to Oura':status.oura.configured?'Ready to connect':'Oura app credentials needed on your server'}</div><p className="small">{synced(status.oura.lastSync)}</p>
 {!status.oura.configured&&<p className="small">Add OURA_CLIENT_ID, OURA_CLIENT_SECRET, and OURA_REDIRECT_URI to .env, then restart the server. See WEARABLES.md for setup.</p>}
 <div className="actions wearable-actions"><button className="primary" disabled={busy||!status.oura.configured} onClick={()=>void act(async()=>{const data=await request('/oura/connect','POST');location.assign(data.url);})}>{status.oura.connected?'Review permissions':'Connect Oura →'}</button>
 {status.oura.connected&&<><button className="secondary" disabled={busy} onClick={()=>void act(async()=>{const data=await request('/oura/sync','POST');await onImported();setMessage(`${data.inserted} new readings imported; ${data.updated} updated. Empty results can mean your ring has not synced yet or a permission is off.`);})}>{busy?'Please wait…':'Sync last 7 days'}</button><button className="text-button" disabled={busy} onClick={()=>void act(async()=>{setMessage((await request('/oura','DELETE')).message);})}>Disconnect Oura</button></>}
 </div><p className="small">Sync your ring in the Oura app first. This imports available history on request; it is not a live monitor. Disconnecting here leaves saved entries intact. Revoke access in Oura settings to remove the provider authorization too.</p></section>
 <section className="panel"><span className="large-symbol">⌚</span><h2>Apple Watch</h2><p>The PulseSense iPhone companion reads Watch measurements from Apple Health with your permission, then uploads them when you press Sync.</p><div className="notice">{status.apple.connected?'iPhone companion paired':'iPhone companion setup required'}</div><p className="small">{synced(status.apple.lastSync)}</p><ol className="wearable-steps"><li>Install the included iPhone companion using Xcode.</li><li>Enter this server’s HTTPS address in the companion.</li><li>Generate a code here and paste it into the companion.</li><li>Allow Health access, then tap Sync last 7 days on your phone.</li></ol>
 <div className="actions wearable-actions"><button className="primary" disabled={busy} onClick={()=>void act(async()=>{setPair(await request('/apple/pair-code','POST'));})}>{status.apple.connected?'Pair another iPhone':'Generate pairing code'}</button>{status.apple.connected&&<button className="text-button" disabled={busy} onClick={()=>void act(async()=>{setMessage((await request('/apple-health','DELETE')).message);setPair(null);})}>Disconnect iPhone</button>}</div>
 {pair&&<div className="notice"><strong>One-time pairing code</strong><code className="pair-code">{pair.code}</code><p className="small">Expires {new Date(pair.expires).toLocaleTimeString()}. Treat this code like a password. Pairing another phone replaces access for the previous one.</p><button className="text-button" onClick={()=>setPair(null)}>Hide code</button></div>}
 <p className="small">This website cannot read Apple Health directly. A phone cannot reach your Mac through “localhost.” Use a reachable HTTPS server. See WEARABLES.md.</p></section></div>}
 <section className="panel audit"><h3>Know what you’re looking at</h3><p>Readings retain their source and measurement time. Apple Health HRV is labeled SDNN; Oura sleep HRV is labeled RMSSD. They are different measurements and should not be treated as interchangeable.</p><p>Missing readings stay empty. Supported measurements depend on device, permissions, region, and whether the wearable has synced. Blood pressure is still manual. Imported data is saved in your PulseSense account and is not automatically sent to Gemini or ElevenLabs.</p></section></>;
}
